#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/ec2-user/.vscode-server/cli/servers/Stable-7c6fdfb0b8f2f675eb0b47f3d95eeca78962565b/server/node" "/home/ec2-user/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"